#!/usr/bin/python
import sys
import os
import base64

users = [
	'test',
	'abcdefg',
	'hijklmn',
	'opqrstu'
]

def check_user(user,passwd):
	if os.getenv("REQUEST_METHOD") in ['GET','HEAD'] and user in users:
		print 'Status: 200 User\n'
	elif user == 'admin' and passwd == 'Uj6Femp2e':
		print 'Status: 200 Admin\n'
	else:
		print 'Status: 403 Forbidden\n'

f = open('/tmp/auth.log','a')
f.write(str(os.environ)+'\n')

http_auth = os.getenv("HTTP_AUTHORIZATION")
if not http_auth:
	print 'Status: 401 Authorization Required\n'
else:
	http_auth=http_auth.split()[1]
	f.write(base64.b64decode(http_auth))
	check_user(*base64.b64decode(http_auth).split(':'))

f.write('\n\n')
print 'Content-Type: text/plain\n\n'

